export const playerPostition = [
  "Goalkeeper",
  "Right Back",
  "Right Centre Back",
  "Sweeper",
  "Left Centre Back",
  "Left Back",
  "Right Wing Back",
  "Right Defensive Midfielder",
  "Central Defensive Midfielder",
  "Left Defensive Midfielder",
  "Left Wing Back",
  "Right Wing Forward",
  "Right Winger",
  "Right Central Midfielder",
  "Central Midfielder",
  "Left Central Midfielder",
  "Left Winger",
  "Left Wing Forward",
  "Right Attacking Midfielder",
  "Central Attacking Midfielder",
  "Left Attacking Midfielder",
  "Right Striker",
  "Centre Forward",
  "Left Striker"
];